2019-10-11 13:12:59,812 - INFO- Analisis temporal para [78.0, 86.0, 94.0, 102.0, 110.0, 118.0, 126.0, 134.0, 142.0]
2019-10-11 13:13:52,340 - INFO- Analisis temporal para [78.0, 86.0, 94.0, 102.0, 110.0, 118.0, 126.0, 134.0, 142.0]
2019-10-11 13:14:15,363 - INFO- Analisis temporal para [78.0, 86.0, 94.0, 102.0, 110.0, 118.0, 126.0, 134.0, 142.0]
2019-10-11 13:14:28,333 - CRITICAL- No hay datos suficientes de espectro para analisis temporal
2019-10-11 13:14:28,333 - INFO- Analisis temporal para 78000000
2019-10-11 13:14:37,434 - CRITICAL- No hay datos suficientes de espectro para analisis temporal
2019-10-11 13:14:37,434 - INFO- Analisis temporal para 78000000
2019-10-11 13:14:40,600 - ERROR- Falta de datos
Traceback (most recent call last):
  File "/home/radiogis/Desktop/CentroTIC/src/project_module3/radioastronomia/views.py", line 261, in analisis_tiempo
    espectro = Espectro.objects.filter(region=region).filter(frec_central=frec_central).filter(frec_muestreo=frec_muestreo).filter(nfft=nfft).filter(fecha__range=[cliente["fechaini"], cliente["fechafin"]])
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/query.py", line 844, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/query.py", line 862, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1263, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1287, in _add_q
    split_subq=split_subq,
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1225, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1096, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/lookups.py", line 210, in get_prep_lookup
    rhs_value = self.lhs.output_field.get_prep_value(rhs_value)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1408, in get_prep_value
    value = super().get_prep_value(value)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1268, in get_prep_value
    return self.to_python(value)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1393, in to_python
    params={'value': value},
django.core.exceptions.ValidationError: ["'' value has an invalid format. It must be in YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] format."]
2019-10-11 13:14:56,636 - INFO- Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2019-10-11 13:14:56,638 - INFO- Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2019-10-11 13:14:57,558 - INFO- Analisis temporal para 78000000
2019-10-11 13:17:14,485 - INFO- Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2019-10-11 13:17:14,487 - INFO- Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2019-10-11 13:17:15,441 - INFO- Analisis temporal para 78000000
2019-10-11 14:00:09,559 - WARNING- Not Found: /media/album/regiones/ec8613f2-dbe7-46aa-8d24-cba241b75900.jpeg
2019-10-11 14:00:14,509 - ERROR- Internal Server Error: /app_praes/medicion_actual/
Traceback (most recent call last):
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column app_praes_ubicacion_lectura.tipo_experimento does not exist
LINE 1: ...pp_praes_ubicacion_lectura"."etiqueta_ubicacion", "app_praes...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column app_praes_ubicacion_lectura.tipo_experimento does not exist
LINE 1: ...pp_praes_ubicacion_lectura"."etiqueta_ubicacion", "app_praes...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/radiogis/Desktop/CentroTIC/src/project_module3/app_praes/views.py", line 55, in medicion_actual_temperatura
    return render(request, "app_praes/temperatura.html", respuesta)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 352, in bootstrap_form
    return render_form(*args, **kwargs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/forms.py", line 62, in render_form
    return renderer_cls(form, **kwargs).render()
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 99, in render
    return mark_safe(self._render())
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 235, in _render
    return self.render_errors(self.error_types) + self.render_fields()
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 198, in render_fields
    bound_css_class=self.bound_css_class,
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/forms.py", line 78, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 99, in render
    return mark_safe(self._render())
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 568, in _render
    html = self.field.as_widget(attrs=self.widget.attrs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/widgets.py", line 229, in render
    context = self.get_context(name, value, attrs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/widgets.py", line 668, in get_context
    context = super().get_context(name, value, attrs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/widgets.py", line 629, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/widgets.py", line 577, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/models.py", line 1139, in __iter__
    for obj in queryset:
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/query.py", line 332, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.close()
psycopg2.OperationalError: cursor "_django_curs_139856331519744_1" does not exist

2019-10-11 14:00:24,716 - ERROR- Internal Server Error: /app_praes/matematica-ambiental/
Traceback (most recent call last):
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column app_praes_ubicacion_lectura.tipo_experimento does not exist
LINE 1: ...pp_praes_ubicacion_lectura"."etiqueta_ubicacion", "app_praes...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1065, in execute_sql
    cursor.execute(sql, params)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 100, in execute
    return super().execute(sql, params)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 68, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 77, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/backends/utils.py", line 85, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column app_praes_ubicacion_lectura.tipo_experimento does not exist
LINE 1: ...pp_praes_ubicacion_lectura"."etiqueta_ubicacion", "app_praes...
                                                             ^


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/radiogis/Desktop/CentroTIC/src/project_module3/app_praes/views.py", line 369, in matematica_ambiental
    return render(request, "app_praes/matematica_ambiental.html", respuesta)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/shortcuts.py", line 36, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 937, in render
    bit = node.render_annotated(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/base.py", line 904, in render_annotated
    return self.render(context)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/template/library.py", line 192, in render
    output = self.func(*resolved_args, **resolved_kwargs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/templatetags/bootstrap3.py", line 352, in bootstrap_form
    return render_form(*args, **kwargs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/forms.py", line 62, in render_form
    return renderer_cls(form, **kwargs).render()
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 99, in render
    return mark_safe(self._render())
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 235, in _render
    return self.render_errors(self.error_types) + self.render_fields()
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 198, in render_fields
    bound_css_class=self.bound_css_class,
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/forms.py", line 78, in render_field
    return renderer_cls(field, **kwargs).render()
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 99, in render
    return mark_safe(self._render())
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/bootstrap3/renderers.py", line 568, in _render
    html = self.field.as_widget(attrs=self.widget.attrs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/widgets.py", line 229, in render
    context = self.get_context(name, value, attrs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/widgets.py", line 668, in get_context
    context = super().get_context(name, value, attrs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/widgets.py", line 629, in get_context
    context['widget']['optgroups'] = self.optgroups(name, context['widget']['value'], attrs)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/widgets.py", line 577, in optgroups
    for index, (option_value, option_label) in enumerate(self.choices):
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/forms/models.py", line 1139, in __iter__
    for obj in queryset:
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/query.py", line 332, in _iterator
    yield from self._iterable_class(self, chunked_fetch=use_chunked_fetch, chunk_size=chunk_size)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/query.py", line 54, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/home/radiogis/Desktop/env_centrotic/lib/python3.6/site-packages/django/db/models/sql/compiler.py", line 1068, in execute_sql
    cursor.close()
psycopg2.OperationalError: cursor "_django_curs_139856331519744_2" does not exist

2019-10-11 15:50:14,686 - WARNING- Not Found: /media/album/regiones/ec8613f2-dbe7-46aa-8d24-cba241b75900.jpeg
2019-10-11 15:50:22,986 - INFO- Analisis temporal para [78.0, 86.0, 94.0, 102.0, 110.0, 118.0, 126.0, 134.0, 142.0]
2019-10-11 15:51:24,820 - INFO- Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2019-10-11 15:51:24,822 - INFO- Using categorical units to plot a list of strings that are all parsable as floats or dates. If these strings should be plotted as numbers, cast to the appropriate data type before plotting.
2019-10-11 15:51:25,836 - INFO- Analisis temporal para 78000000
